# Generated by Django 5.1 on 2024-08-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_rename_fooditem_caritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='caritem',
            name='model',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
