# Generated by Django 5.1 on 2024-08-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_caritem_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('dir', models.CharField(max_length=50)),
            ],
        ),
    ]
